-- 1. Tabla de Contactos (Clientes)
CREATE TABLE IF NOT EXISTS contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    cpf TEXT UNIQUE, -- CPF como llave única para evitar duplicados
    email TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla de Reservas (Cabecera)
CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT REFERENCES contacts(id), -- Relación con el cliente
    total_amount NUMERIC DEFAULT 0,
    total_entry NUMERIC DEFAULT 0,
    total_balance NUMERIC DEFAULT 0,
    currency TEXT DEFAULT 'COP',
    status TEXT DEFAULT 'confirmed', -- confirmed, cancelled, pending
    created_at TIMESTAMPTZ DEFAULT NOW(),
    agent_name TEXT, -- Quién hizo la venta
    metadata JSONB -- Para guardar datos extra del formulario si es necesario
);

-- 3. Tabla de Items de Reserva (Tours específicos)
CREATE TABLE IF NOT EXISTS booking_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT REFERENCES bookings(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id), -- Relación con el catálogo maestro
    tour_date DATE NOT NULL,
    tour_time TEXT,
    pax_adult INTEGER DEFAULT 0,
    pax_chd INTEGER DEFAULT 0,
    price_sale NUMERIC DEFAULT 0,
    price_entry NUMERIC DEFAULT 0,
    hotel TEXT,
    pickup_time TEXT,
    observations TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS (Row Level Security) - Por ahora permitir todo para desarrollo
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE booking_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all for development" ON contacts FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for development" ON bookings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for development" ON booking_items FOR ALL USING (true) WITH CHECK (true);
